//! Build script to generate C header file using cbindgen

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_dir = PathBuf::from(&crate_dir).join("include");

    std::fs::create_dir_all(&output_dir).expect("Failed to create include directory");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("DASHTERM_H".to_string()),
        autogen_warning: Some(
            "/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */"
                .to_string(),
        ),
        documentation_style: cbindgen::DocumentationStyle::C99,
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output_dir.join("dashterm.h"));

    println!("cargo:rerun-if-changed=src/lib.rs");
}
