name: DashTerm
options:
  bundleIdPrefix: com.dashterm
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  DashTerm:
    type: application
    platform: macOS
    sources:
      - path: DashTerm
        excludes:
          - "Bridge/dashterm.h"
          - "Bridge/libdashterm_ffi.a"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dashterm.DashTerm
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_OBJC_BRIDGING_HEADER: $(PROJECT_DIR)/DashTerm/Bridge/DashTerm-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - $(PROJECT_DIR)/DashTerm/Bridge
        LIBRARY_SEARCH_PATHS:
          - $(PROJECT_DIR)/DashTerm/Bridge
        OTHER_LDFLAGS:
          - -ldashterm_ffi
          - -lresolv
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: NO
    dependencies: []
