#!/bin/bash
# Generate BuildInfo.swift with build timestamp and git info

OUTPUT_FILE="${SRCROOT}/sources/BuildInfo.generated.swift"

# Get git info
GIT_COMMIT=$(git -C "${SRCROOT}" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git -C "${SRCROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_DIRTY=$(git -C "${SRCROOT}" diff --quiet 2>/dev/null && echo "" || echo "-dirty")

# Get build timestamp
BUILD_TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
BUILD_DATE=$(date "+%Y%m%d")
BUILD_TIME=$(date "+%H%M%S")

# Get version from plist
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${SRCROOT}/plists/DashTerm2.plist" 2>/dev/null || echo "0.0.0")

cat > "${OUTPUT_FILE}" << EOF
// BuildInfo.generated.swift
// Auto-generated by generate-build-info.sh - DO NOT EDIT

import Foundation

@objc public class BuildInfo: NSObject {
    @objc public static let appVersion = "${VERSION}"
    @objc public static let buildNumber = "${BUILD_DATE}.${BUILD_TIME}"
    @objc public static let gitCommit = "${GIT_COMMIT}${GIT_DIRTY}"
    @objc public static let gitBranch = "${GIT_BRANCH}"
    @objc public static let buildTimestamp = "${BUILD_TIMESTAMP}"

    @objc public static var fullVersionString: String {
        return "\(appVersion) (\(buildNumber))"
    }

    @objc public static var buildInfoString: String {
        return """
        DashTerm2 v\(appVersion)
        Build: \(buildNumber)
        Git: \(gitBranch)@\(gitCommit)
        Built: \(buildTimestamp)
        """
    }
}
EOF

echo "Generated ${OUTPUT_FILE}"
