// ESLint configuration for DashTerm2 JavaScript files
// Template files with {{VAR}} syntax are excluded as they can't be parsed

module.exports = [
  {
    ignores: [
      "ThirdParty/**",
      "submodules/**",
      "node_modules/**",
      "*.min.js",
      "eslint.config.js",
      // Template files with {{VAR}} syntax that can't be parsed
      "sources/Browser/Local Pages/welcome-page.js",
      "sources/Browser/Audio Muting/monitor-play.js",
      "sources/Browser/Audio Muting/mute-audio.js",
      "sources/Browser/Audio Muting/monitor-audio-context.js",
      "sources/Browser/Core/hover-link-detector.js",
      "sources/Browser/Core/monitor-selection.js",
      "sources/Browser/Core/monitor-context-menu.js",
      "sources/Browser/Core/console-log.js",
      "sources/Browser/Marks/show-named-mark-annotations.js",
      "sources/Browser/Marks/update-mark-positions.js",
      "sources/Browser/Marks/get-xpath-at-point.js",
      "sources/Browser/Marks/navigate-to-named-mark.js",
      "sources/Browser/Triggers/triggers.js",
      "sources/Browser/Autofill/autofill-fill-all.js",
      "sources/Browser/Autofill/autofill-write.js",
      "sources/Browser/Autofill/autofill-detector.js",
      "sources/Browser/WebView Additions/extend-selection-word.js",
      "sources/Browser/WebView Additions/open-link-at-point.js",
      "sources/Browser/WebView Additions/extend-selection-character.js",
      "sources/Browser/WebView Additions/extend-selection-bigword.js",
      "sources/Browser/WebView Additions/extract-text-at-point.js",
      "sources/Browser/WebView Additions/extend-selection-line.js",
      "sources/Browser/WebView Additions/insert-text.js",
      "sources/Browser/WebView Additions/urls-at-point.js",
      "sources/Browser/WebView Additions/extend-selection-to-point.js",
      "sources/Browser/WebView Additions/select-text.js",
      "sources/Browser/Copy Mode/copy-mode.js",
      "sources/Browser/Editing Detector/editing-detector.js",
      "sources/Browser/Find on Page/find-constants.js",
      "sources/Browser/Find on Page/find-engine.js",
      "sources/Browser/Find on Page/custom-find.js",
      "sources/Browser/Ad Blocking/adblock-css-injection.js",
      "sources/Browser/Polyfills/geolocation-bridge.js",
      "sources/Browser/Polyfills/notification-bridge.js",
      "sources/Browser/Reader Mode/load-readability.js",
      "sources/Browser/Reader Mode/load-reader-mode.js",
      "sources/Browser/Reader Mode/remove-element-at-point.js",
      "sources/Browser/Reader Mode/reader-mode-with-styles.js",
      "sources/Browser/Reader Mode/convert-to-markdown.js",
      "sources/Browser/Password Manager/password-button.js",
      "sources/Browser/Password Manager/write-password.js",
      "sources/Browser/Password Manager/focus-password.js",
    ],
  },
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        webkit: "readonly",
        chrome: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Node: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLMediaElement: "readonly",
        Event: "readonly",
        MutationObserver: "readonly",
        Range: "readonly",
        Selection: "readonly",
        getComputedStyle: "readonly",
        requestAnimationFrame: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        location: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        confirm: "readonly",
        alert: "readonly",
        prompt: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
        TreeWalker: "readonly",
        NodeFilter: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        Image: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        performance: "readonly",
        self: "readonly",
        parent: "readonly",
        top: "readonly",
        frameElement: "readonly",
      },
    },
    rules: {
      "no-undef": "warn",
      "no-unused-vars": "off",
      "no-redeclare": "warn",
      "no-empty": "warn",
      "no-constant-condition": "warn",
    },
  },
];
