#ifndef DASHTERM_H
#define DASHTERM_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque graph handle
typedef struct DashTermGraph DashTermGraph;

// Opaque terminal handle
typedef struct DashTermTerminal DashTermTerminal;

// Terminal size
typedef struct DashTermSize {
  uint32_t cols;
  uint32_t rows;
} DashTermSize;

// Cursor position and visibility
typedef struct DashTermCursor {
  uint32_t row;
  uint32_t col;
  bool visible;
} DashTermCursor;

// Zoom-to-fit result with zoom level and pan offsets
typedef struct DashTermZoomFit {
  float zoom;
  float pan_x;
  float pan_y;
} DashTermZoomFit;

// Create a new terminal instance
struct DashTermTerminal *dashterm_terminal_new(uint32_t cols, uint32_t rows);

// Free a terminal instance
void dashterm_terminal_free(struct DashTermTerminal *ptr);

// Process input bytes from PTY
void dashterm_terminal_process(struct DashTermTerminal *ptr, const uint8_t *data, uintptr_t len);

// Resize the terminal
void dashterm_terminal_resize(struct DashTermTerminal *ptr, uint32_t cols, uint32_t rows);

// Get terminal size
struct DashTermSize dashterm_terminal_get_size(const struct DashTermTerminal *ptr);

// Get cursor position
struct DashTermCursor dashterm_terminal_get_cursor(const struct DashTermTerminal *ptr);

// Get the terminal grid as JSON
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_grid_json(const struct DashTermTerminal *ptr);

// Get the window title
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_title(const struct DashTermTerminal *ptr);

// Get pending terminal events as JSON
// Returns events like Bell, TitleChanged, Exit, Redraw
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_events_json(struct DashTermTerminal *ptr);

// Get damaged lines for efficient partial updates as JSON
// Returns array of [line, left_col, right_col] tuples
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_damage_json(struct DashTermTerminal *ptr);

// Reset damage tracking after rendering
void dashterm_terminal_reset_damage(struct DashTermTerminal *ptr);

// Enable agent output parsing for the terminal
// Agent events will be collected and can be retrieved with dashterm_terminal_get_agent_events_json
void dashterm_terminal_enable_agent_parsing(struct DashTermTerminal *ptr);

// Disable agent output parsing
void dashterm_terminal_disable_agent_parsing(struct DashTermTerminal *ptr);

// Check if agent parsing is enabled
bool dashterm_terminal_is_agent_parsing_enabled(const struct DashTermTerminal *ptr);

// Get pending agent events as JSON
// Returns JSON array of AgentEvent objects
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_agent_events_json(struct DashTermTerminal *ptr);

// Get the currently active agent node ID (if any)
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_active_agent_node(const struct DashTermTerminal *ptr);

// Get the currently active agent tool name (if any)
// Caller must free the returned string with dashterm_string_free
char *dashterm_terminal_get_active_agent_tool(const struct DashTermTerminal *ptr);

// Clear agent parser state
void dashterm_terminal_clear_agent_state(struct DashTermTerminal *ptr);

// Get the current scroll display offset (0 = bottom, positive = scrolled up)
uint32_t dashterm_terminal_get_display_offset(const struct DashTermTerminal *ptr);

// Get the total number of history lines available for scrolling
uint32_t dashterm_terminal_get_history_size(const struct DashTermTerminal *ptr);

// Scroll the display up by the given number of lines
void dashterm_terminal_scroll_up(struct DashTermTerminal *ptr, uint32_t lines);

// Scroll the display down by the given number of lines
void dashterm_terminal_scroll_down(struct DashTermTerminal *ptr, uint32_t lines);

// Scroll to the top of history
void dashterm_terminal_scroll_to_top(struct DashTermTerminal *ptr);

// Scroll to the bottom (most recent output)
void dashterm_terminal_scroll_to_bottom(struct DashTermTerminal *ptr);

// Create a new computation graph
struct DashTermGraph *dashterm_graph_new(const char *name);

// Free a graph instance
void dashterm_graph_free(struct DashTermGraph *ptr);

// Add a node to the graph
// Returns the node ID or null on failure
char *dashterm_graph_add_node(struct DashTermGraph *ptr,
                              const char *id,
                              const char *label,
                              uint32_t node_type);

// Add an edge to the graph
// Returns true on success
bool dashterm_graph_add_edge(struct DashTermGraph *ptr,
                             const char *from_id,
                             const char *to_id,
                             uint32_t edge_type);

// Get the graph layout data as JSON
// Caller must free the returned string with dashterm_string_free
char *dashterm_graph_get_layout_json(const struct DashTermGraph *ptr);

// Compute auto-layout for all nodes in the graph
// Uses a hierarchical/layered algorithm based on topological depth
void dashterm_graph_compute_layout(struct DashTermGraph *ptr);

// Compute zoom and pan values to fit all nodes in a viewport of the given size.
// Returns a DashTermZoomFit struct with zoom, pan_x, and pan_y values.
struct DashTermZoomFit dashterm_graph_compute_zoom_to_fit(const struct DashTermGraph *ptr,
                                                          float viewport_width,
                                                          float viewport_height);

// Get the bounding box of all nodes in the graph as JSON
// Returns JSON with min_x, min_y, max_x, max_y
// Caller must free the returned string with dashterm_string_free
char *dashterm_graph_get_bounding_box_json(const struct DashTermGraph *ptr);

// Create a node group in the graph
// Returns the group ID or null on failure
char *dashterm_graph_create_group(struct DashTermGraph *ptr,
                                  const char *group_id,
                                  const char *label);

// Add a node to a group
// Returns true on success
bool dashterm_graph_add_node_to_group(struct DashTermGraph *ptr,
                                      const char *node_id,
                                      const char *group_id);

// Toggle a group's collapsed state
// Returns the new collapsed state (true = collapsed, false = expanded)
bool dashterm_graph_toggle_group(struct DashTermGraph *ptr, const char *group_id);

// Automatically group consecutive tool nodes under model nodes
// Returns the number of groups created
uint32_t dashterm_graph_auto_group_tools(struct DashTermGraph *ptr, uint32_t min_tools);

// Update a group's status based on its child nodes
void dashterm_graph_update_group_status(struct DashTermGraph *ptr, const char *group_id);

// Free a string allocated by the library
void dashterm_string_free(char *ptr);

// Get the library version
const char *dashterm_version(void);

#endif  /* DASHTERM_H */
