// BuildInfo.generated.swift
// Auto-generated by generate-build-info.sh - DO NOT EDIT

import Foundation

@objc public class BuildInfo: NSObject {
    @objc public static let appVersion = "0.1.0"
    @objc public static let buildNumber = "20251231.051939"
    @objc public static let gitCommit = "21d4c25bd-dirty"
    @objc public static let gitBranch = "main"
    @objc public static let buildTimestamp = "2025-12-31 05:19:39"

    @objc public static var fullVersionString: String {
        return "\(appVersion) (\(buildNumber))"
    }

    @objc public static var buildInfoString: String {
        return """
        DashTerm2 v\(appVersion)
        Build: \(buildNumber)
        Git: \(gitBranch)@\(gitCommit)
        Built: \(buildTimestamp)
        """
    }
}
