#!/usr/bin/env node

/**
 * Capture PNG screenshots for the Codex LeetCode integration test snapshots.
 *
 * Usage:
 *   node scripts/capture_codex_leetcode_screenshots.js
 *
 * Inputs (generated by `examples/apps/codex-dashflow/tests/leetcode_integration.rs`):
 *   ~/Desktop/codex_leetcode_*.html
 *
 * Outputs:
 *   ~/Desktop/codex_leetcode_*.png
 */

const os = require('os');
const path = require('path');
const fs = require('fs');

let chromium;
try {
  ({ chromium } = require('playwright'));
} catch (err) {
  console.error('Playwright is not installed or not resolvable from repo root.');
  console.error('Try: npm install && npm run install:playwright');
  console.error(err?.message ?? err);
  process.exit(1);
}

const desktopDir = process.env.DASHFLOW_DESKTOP_DIR || path.join(os.homedir(), 'Desktop');

const snapshotStems = [
  'codex_leetcode_graph_start',
  'codex_leetcode_agent_thinking',
  'codex_leetcode_tool_calls',
  'codex_leetcode_streaming',
  'codex_leetcode_final_state',
];

async function main() {
  if (!fs.existsSync(desktopDir)) {
    console.error(`Desktop directory not found: ${desktopDir}`);
    process.exit(1);
  }

  const targets = snapshotStems.map(stem => {
    const htmlPath = path.join(desktopDir, `${stem}.html`);
    const pngPath = path.join(desktopDir, `${stem}.png`);
    return { stem, htmlPath, pngPath };
  });

  let missing = 0;
  for (const t of targets) {
    if (!fs.existsSync(t.htmlPath)) missing += 1;
  }
  if (missing === targets.length) {
    console.error(`No snapshot HTML files found in: ${desktopDir}`);
    console.error('Run the LeetCode integration test first:');
    console.error('  cargo test -p codex-dashflow --test leetcode_integration -- --ignored --nocapture');
    process.exit(2);
  }

  const browser = await chromium.launch();
  const page = await browser.newPage({
    viewport: { width: 1280, height: 720 },
  });

  let rendered = 0;
  let hadMissing = false;

  for (const { stem, htmlPath, pngPath } of targets) {
    if (!fs.existsSync(htmlPath)) {
      console.warn(`Missing: ${htmlPath}`);
      hadMissing = true;
      continue;
    }

    console.log(`Capturing: ${stem}`);
    await page.goto(`file://${htmlPath}`);
    await page.waitForTimeout(100);
    await page.screenshot({ path: pngPath, fullPage: true });
    const stats = fs.statSync(pngPath);
    console.log(`  Wrote: ${pngPath} (${(stats.size / 1024).toFixed(1)}KB)`);
    rendered += 1;
  }

  await browser.close();

  if (rendered === 0) {
    console.error('No screenshots captured.');
    process.exit(3);
  }

  if (hadMissing) {
    console.warn('Some snapshot HTML files were missing; not all PNGs were captured.');
    process.exit(4);
  }

  console.log(`Done. Captured ${rendered} screenshots to ${desktopDir}`);
}

main().catch(err => {
  console.error('Error capturing Codex LeetCode screenshots:');
  console.error(err);
  process.exit(1);
});

