#!/bin/bash
# Script to remove remaining unused dependencies detected by cargo-machete
# Generated by AI Worker N=1072
# © 2025 Dropbox (created by Andrew Yates <ayates@dropbox.com>)

set -euo pipefail

echo "Cleaning up remaining unused dependencies..."

# Note: Skipping milvus-sdk-rust as it's a false positive (lib name is 'milvus')

# dashflow-langserve
cargo remove flate2 schemars tower --package dashflow-langserve 2>/dev/null || true

# dashflow-playwright
cargo remove thiserror --package dashflow-playwright 2>/dev/null || true

# dashflow-replicate
cargo remove anyhow serde thiserror --package dashflow-replicate 2>/dev/null || true

# dashflow-nomic
cargo remove thiserror --package dashflow-nomic 2>/dev/null || true

# dashflow-annoy
cargo remove anyhow serde_json thiserror --package dashflow-annoy 2>/dev/null || true

# dashflow-remote-node
cargo remove thiserror --package dashflow-remote-node 2>/dev/null || true

# dashflow-cohere
cargo remove anyhow --package dashflow-cohere 2>/dev/null || true

# dashflow-cassandra
cargo remove futures prost prost-types thiserror --package dashflow-cassandra 2>/dev/null || true

# dashflow-deepseek
cargo remove anyhow thiserror --package dashflow-deepseek 2>/dev/null || true

# dashflow-postgres-checkpointer
cargo remove tokio tracing --package dashflow-postgres-checkpointer 2>/dev/null || true

# dashflow-json-tool
cargo remove serde serde_json uuid --package dashflow-json-tool 2>/dev/null || true

# dashflow-hnsw
cargo remove serde thiserror --package dashflow-hnsw 2>/dev/null || true

# dashflow-groq
cargo remove anyhow --package dashflow-groq 2>/dev/null || true

# dashflow-neo4j
cargo remove thiserror --package dashflow-neo4j 2>/dev/null || true

# dashflow-file-management
cargo remove anyhow serde thiserror --package dashflow-file-management 2>/dev/null || true

# dashflow-clickhouse
cargo remove thiserror --package dashflow-clickhouse 2>/dev/null || true

# dashflow-anthropic
cargo remove anyhow --package dashflow-anthropic 2>/dev/null || true

# dashflow-redis
cargo remove thiserror --package dashflow-redis 2>/dev/null || true

# dashflow-together
cargo remove anyhow --package dashflow-together 2>/dev/null || true

# dashflow-duckduckgo
cargo remove anyhow --package dashflow-duckduckgo 2>/dev/null || true

# dashflow-usearch
cargo remove serde thiserror tokio tracing --package dashflow-usearch 2>/dev/null || true

# dashflow-bedrock
cargo remove anyhow --package dashflow-bedrock 2>/dev/null || true

# dashflow-shell-tool
cargo remove anyhow --package dashflow-shell-tool 2>/dev/null || true

# dashflow-openapi
cargo remove serde --package dashflow-openapi 2>/dev/null || true

# dashflow-langsmith
cargo remove serde thiserror --package dashflow-langsmith 2>/dev/null || true

# dashflow-wasm-executor
cargo remove thiserror --package dashflow-wasm-executor 2>/dev/null || true

# dashflow-qdrant
cargo remove serde --package dashflow-qdrant 2>/dev/null || true

# dashflow
cargo remove serde --package dashflow 2>/dev/null || true

# dashflow-observability
cargo remove anyhow serde --package dashflow-observability 2>/dev/null || true

# dashflow-clickup
cargo remove thiserror --package dashflow-clickup 2>/dev/null || true

# dashflow-reddit
cargo remove anyhow --package dashflow-reddit 2>/dev/null || true

# dashflow-wolfram
cargo remove thiserror --package dashflow-wolfram 2>/dev/null || true

# dashflow-xai
cargo remove anyhow --package dashflow-xai 2>/dev/null || true

# dashflow-slack
cargo remove thiserror --package dashflow-slack 2>/dev/null || true

# dashflow-github
cargo remove anyhow --package dashflow-github 2>/dev/null || true

# dashflow-json
cargo remove anyhow --package dashflow-json 2>/dev/null || true

# dashflow-weaviate
cargo remove thiserror --package dashflow-weaviate 2>/dev/null || true

# dashflow-sql-database
cargo remove thiserror --package dashflow-sql-database 2>/dev/null || true

echo "Cleanup complete! Running cargo check..."
cargo check --workspace

echo "Done!"
