#!/bin/bash
# generate_docs.sh - Generate API reference documentation from rustdoc
#
# M-390: API reference docs from rustdoc (build/publish pipeline; searchable index)
#
# Usage:
#   ./scripts/generate_docs.sh           # Generate docs for all crates
#   ./scripts/generate_docs.sh --open    # Generate and open in browser
#   ./scripts/generate_docs.sh --json    # Also generate JSON index for search
#   ./scripts/generate_docs.sh --serve   # Serve docs on localhost:8000
#   ./scripts/generate_docs.sh dashflow-openai  # Generate docs for specific crate
#
# Output:
#   target/doc/                          # HTML documentation
#   target/doc/dashflow/index.html       # Main entry point (core crate)
#   docs/API_INDEX.md                    # Generated searchable index

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOC_DIR="$PROJECT_ROOT/target/doc"
API_INDEX="$PROJECT_ROOT/docs/API_INDEX.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_section() { echo -e "\n${CYAN}=== $1 ===${NC}"; }

# Parse arguments
OPEN_BROWSER=false
GENERATE_JSON=false
SERVE_DOCS=false
SPECIFIC_CRATE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --open)
            OPEN_BROWSER=true
            shift
            ;;
        --json)
            GENERATE_JSON=true
            shift
            ;;
        --serve)
            SERVE_DOCS=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS] [CRATE]"
            echo ""
            echo "Options:"
            echo "  --open    Open documentation in browser after generation"
            echo "  --json    Generate JSON search index"
            echo "  --serve   Serve documentation on localhost:8000"
            echo "  --help    Show this help message"
            echo ""
            echo "Arguments:"
            echo "  CRATE     Generate docs for specific crate (e.g., dashflow-openai)"
            echo ""
            echo "Examples:"
            echo "  $0                      # Generate all docs"
            echo "  $0 --open               # Generate and open in browser"
            echo "  $0 dashflow-streaming   # Docs for specific crate"
            echo "  $0 --serve              # Start local documentation server"
            exit 0
            ;;
        -*)
            log_error "Unknown option: $1"
            exit 1
            ;;
        *)
            SPECIFIC_CRATE="$1"
            shift
            ;;
    esac
done

cd "$PROJECT_ROOT"

log_section "DashFlow API Documentation Generator"

# Build documentation flags
DOC_FLAGS=(
    --workspace
    --no-deps
)

# Rustdoc flags for better documentation
# --cfg docsrs: Enable doc features for conditional compilation
# --enable-index-page: Create an index page (requires nightly)
export RUSTDOCFLAGS="--cfg docsrs"

if [[ -n "$SPECIFIC_CRATE" ]]; then
    log_info "Building docs for: $SPECIFIC_CRATE"
    DOC_FLAGS=(-p "$SPECIFIC_CRATE" --no-deps)
fi

# Generate documentation
log_info "Running cargo doc..."
if timeout 600 cargo doc "${DOC_FLAGS[@]}" 2>&1; then
    log_success "Documentation generated successfully"
else
    log_error "Documentation generation failed or timed out"
    exit 1
fi

# Count documented crates
CRATE_COUNT=$(find "$DOC_DIR" -maxdepth 1 -type d -name "dashflow*" 2>/dev/null | wc -l | tr -d ' ')
log_info "Documented crates: $CRATE_COUNT"

# Generate API index
log_section "Generating API Index"

cat > "$API_INDEX" << 'EOF'
# DashFlow API Index

**Auto-generated:** This file is generated by `scripts/generate_docs.sh`
**View full docs:** `./scripts/generate_docs.sh --open`

## Quick Links

| Category | Crates | Description |
|----------|--------|-------------|
| **Core** | [dashflow](./target/doc/dashflow/index.html) | Core graph engine, state management, execution |
| **CLI** | [dashflow-cli](./target/doc/dashflow_cli/index.html) | Command-line interface |
| **Streaming** | [dashflow-streaming](./target/doc/dashflow_streaming/index.html) | Ultra-efficient telemetry protocol |
| **Observability** | [dashflow-observability](./target/doc/dashflow_observability/index.html) | Metrics, tracing, health checks |

## LLM Providers

| Provider | Crate | Features |
|----------|-------|----------|
| OpenAI | [dashflow-openai](./target/doc/dashflow_openai/index.html) | GPT-4, GPT-3.5, embeddings |
| Anthropic | [dashflow-anthropic](./target/doc/dashflow_anthropic/index.html) | Claude models |
| Azure OpenAI | [dashflow-azure-openai](./target/doc/dashflow_azure_openai/index.html) | Azure-hosted OpenAI |
| Google Gemini | [dashflow-gemini](./target/doc/dashflow_gemini/index.html) | Gemini Pro/Ultra |
| AWS Bedrock | [dashflow-bedrock](./target/doc/dashflow_bedrock/index.html) | Claude, Titan, etc. |
| Ollama | [dashflow-ollama](./target/doc/dashflow_ollama/index.html) | Local models |
| Groq | [dashflow-groq](./target/doc/dashflow_groq/index.html) | Fast inference |
| Mistral | [dashflow-mistral](./target/doc/dashflow_mistral/index.html) | Mistral models |
| Cohere | [dashflow-cohere](./target/doc/dashflow_cohere/index.html) | Command, embeddings |
| Together | [dashflow-together](./target/doc/dashflow_together/index.html) | Open source models |
| Replicate | [dashflow-replicate](./target/doc/dashflow_replicate/index.html) | Model marketplace |
| DeepSeek | [dashflow-deepseek](./target/doc/dashflow_deepseek/index.html) | DeepSeek models |
| Fireworks | [dashflow-fireworks](./target/doc/dashflow_fireworks/index.html) | Fast open source |
| Perplexity | [dashflow-perplexity](./target/doc/dashflow_perplexity/index.html) | Search-augmented |
| xAI | [dashflow-xai](./target/doc/dashflow_xai/index.html) | Grok models |
| Cloudflare | [dashflow-cloudflare](./target/doc/dashflow_cloudflare/index.html) | Workers AI |
| HuggingFace | [dashflow-huggingface](./target/doc/dashflow_huggingface/index.html) | HF Inference API |

## Vector Stores

| Store | Crate | Type |
|-------|-------|------|
| Chroma | [dashflow-chroma](./target/doc/dashflow_chroma/index.html) | Embedded |
| Qdrant | [dashflow-qdrant](./target/doc/dashflow_qdrant/index.html) | Cloud/Self-hosted |
| Pinecone | [dashflow-pinecone](./target/doc/dashflow_pinecone/index.html) | Cloud |
| Elasticsearch | [dashflow-elasticsearch](./target/doc/dashflow_elasticsearch/index.html) | Search |
| OpenSearch | [dashflow-opensearch](./target/doc/dashflow_opensearch/index.html) | Search |
| PGVector | [dashflow-pgvector](./target/doc/dashflow_pgvector/index.html) | PostgreSQL |
| Supabase | [dashflow-supabase](./target/doc/dashflow_supabase/index.html) | Postgres-based |
| MongoDB | [dashflow-mongodb](./target/doc/dashflow_mongodb/index.html) | Document store |
| Weaviate | [dashflow-weaviate](./target/doc/dashflow_weaviate/index.html) | GraphQL |
| LanceDB | [dashflow-lancedb](./target/doc/dashflow_lancedb/index.html) | Embedded |
| Redis | [dashflow-redis](./target/doc/dashflow_redis/index.html) | In-memory |
| Neo4j | [dashflow-neo4j](./target/doc/dashflow_neo4j/index.html) | Graph |
| Cassandra | [dashflow-cassandra](./target/doc/dashflow_cassandra/index.html) | Distributed |
| SQLite VSS | [dashflow-sqlitevss](./target/doc/dashflow_sqlitevss/index.html) | Embedded |
| Typesense | [dashflow-typesense](./target/doc/dashflow_typesense/index.html) | Search |
| HNSW | [dashflow-hnsw](./target/doc/dashflow_hnsw/index.html) | In-memory |
| Annoy | [dashflow-annoy](./target/doc/dashflow_annoy/index.html) | Approximate |
| uSearch | [dashflow-usearch](./target/doc/dashflow_usearch/index.html) | High-performance |

## Embedding Providers

| Provider | Crate |
|----------|-------|
| OpenAI | [dashflow-openai](./target/doc/dashflow_openai/index.html) |
| Voyage | [dashflow-voyage](./target/doc/dashflow_voyage/index.html) |
| Cohere | [dashflow-cohere](./target/doc/dashflow_cohere/index.html) |
| Jina | [dashflow-jina](./target/doc/dashflow_jina/index.html) |
| Nomic | [dashflow-nomic](./target/doc/dashflow_nomic/index.html) |
| HuggingFace | [dashflow-huggingface](./target/doc/dashflow_huggingface/index.html) |

## Tools

| Tool | Crate | Purpose |
|------|-------|---------|
| Web Scrape | [dashflow-webscrape](./target/doc/dashflow_webscrape/index.html) | HTML extraction |
| Wikipedia | [dashflow-wikipedia](./target/doc/dashflow_wikipedia/index.html) | Wikipedia search |
| arXiv | [dashflow-arxiv](./target/doc/dashflow_arxiv/index.html) | Academic papers |
| YouTube | [dashflow-youtube](./target/doc/dashflow_youtube/index.html) | Transcripts |
| Google Search | [dashflow-google-search](./target/doc/dashflow_google_search/index.html) | Web search |
| DuckDuckGo | [dashflow-duckduckgo](./target/doc/dashflow_duckduckgo/index.html) | Privacy search |
| Tavily | [dashflow-tavily](./target/doc/dashflow_tavily/index.html) | AI search |
| Brave | [dashflow-brave](./target/doc/dashflow_brave/index.html) | Brave search |
| Bing | [dashflow-bing](./target/doc/dashflow_bing/index.html) | Bing search |
| Exa | [dashflow-exa](./target/doc/dashflow_exa/index.html) | Neural search |
| Serper | [dashflow-serper](./target/doc/dashflow_serper/index.html) | Google API |
| PubMed | [dashflow-pubmed](./target/doc/dashflow_pubmed/index.html) | Medical papers |
| Wolfram | [dashflow-wolfram](./target/doc/dashflow_wolfram/index.html) | Computation |
| Calculator | [dashflow-calculator](./target/doc/dashflow_calculator/index.html) | Math |
| Weather | [dashflow-openweathermap](./target/doc/dashflow_openweathermap/index.html) | Weather data |
| JSON | [dashflow-json-tool](./target/doc/dashflow_json_tool/index.html) | JSON manipulation |
| File | [dashflow-file-tool](./target/doc/dashflow_file_tool/index.html) | File operations |
| Shell | [dashflow-shell-tool](./target/doc/dashflow_shell_tool/index.html) | Command execution |
| Git | [dashflow-git-tool](./target/doc/dashflow_git_tool/index.html) | Git operations |
| HTTP | [dashflow-http-requests](./target/doc/dashflow_http_requests/index.html) | HTTP requests |
| GraphQL | [dashflow-graphql](./target/doc/dashflow_graphql/index.html) | GraphQL queries |
| SQL | [dashflow-sql-database](./target/doc/dashflow_sql_database/index.html) | Database queries |

## Platform Integrations

| Platform | Crate |
|----------|-------|
| GitHub | [dashflow-github](./target/doc/dashflow_github/index.html) |
| GitLab | [dashflow-gitlab](./target/doc/dashflow_gitlab/index.html) |
| Slack | [dashflow-slack](./target/doc/dashflow_slack/index.html) |
| Jira | [dashflow-jira](./target/doc/dashflow_jira/index.html) |
| ClickUp | [dashflow-clickup](./target/doc/dashflow_clickup/index.html) |
| Reddit | [dashflow-reddit](./target/doc/dashflow_reddit/index.html) |
| StackExchange | [dashflow-stackexchange](./target/doc/dashflow_stackexchange/index.html) |
| Gmail | [dashflow-gmail](./target/doc/dashflow_gmail/index.html) |
| Office 365 | [dashflow-office365](./target/doc/dashflow_office365/index.html) |
| LangSmith | [dashflow-langsmith](./target/doc/dashflow_langsmith/index.html) |

## Infrastructure

| Component | Crate |
|-----------|-------|
| Text Splitters | [dashflow-text-splitters](./target/doc/dashflow_text_splitters/index.html) |
| Memory | [dashflow-memory](./target/doc/dashflow_memory/index.html) |
| Context | [dashflow-context](./target/doc/dashflow_context/index.html) |
| Prompts | [dashflow-prompts](./target/doc/dashflow_prompts/index.html) |
| Chains | [dashflow-chains](./target/doc/dashflow_chains/index.html) |
| Compression | [dashflow-compression](./target/doc/dashflow_compression/index.html) |
| JSON | [dashflow-json](./target/doc/dashflow_json/index.html) |
| Registry | [dashflow-registry](./target/doc/dashflow_registry/index.html) |
| Evals | [dashflow-evals](./target/doc/dashflow_evals/index.html) |
| Testing | [dashflow-testing](./target/doc/dashflow_testing/index.html) |

## Checkpointers

| Backend | Crate |
|---------|-------|
| PostgreSQL | [dashflow-postgres-checkpointer](./target/doc/dashflow_postgres_checkpointer/index.html) |
| Redis | [dashflow-redis-checkpointer](./target/doc/dashflow_redis_checkpointer/index.html) |
| S3 | [dashflow-s3-checkpointer](./target/doc/dashflow_s3_checkpointer/index.html) |
| DynamoDB | [dashflow-dynamodb-checkpointer](./target/doc/dashflow_dynamodb_checkpointer/index.html) |

## Generated Documentation

To regenerate this index and full API docs:

```bash
./scripts/generate_docs.sh --open
```

To search within the documentation, use your browser's find function (Ctrl+F / Cmd+F)
or the rustdoc search bar in the generated HTML.
EOF

log_success "API index generated: $API_INDEX"

# Serve documentation if requested
if [[ "$SERVE_DOCS" == "true" ]]; then
    log_section "Serving Documentation"
    log_info "Starting documentation server at http://localhost:8000"
    log_info "Press Ctrl+C to stop"
    cd "$DOC_DIR"
    if command -v python3 &> /dev/null; then
        python3 -m http.server 8000
    else
        log_error "python3 not found. Cannot serve documentation."
        log_info "Install python3 or use: cd target/doc && python3 -m http.server 8000"
        exit 1
    fi
fi

# Open in browser if requested
if [[ "$OPEN_BROWSER" == "true" ]]; then
    INDEX_FILE="$DOC_DIR/dashflow/index.html"
    if [[ ! -f "$INDEX_FILE" ]]; then
        INDEX_FILE="$DOC_DIR/index.html"
    fi

    if [[ -f "$INDEX_FILE" ]]; then
        log_info "Opening documentation in browser..."
        if command -v open &> /dev/null; then
            open "$INDEX_FILE"
        elif command -v xdg-open &> /dev/null; then
            xdg-open "$INDEX_FILE"
        else
            log_warn "Could not open browser. Documentation available at: $INDEX_FILE"
        fi
    else
        log_warn "No index.html found to open"
    fi
fi

# Print summary
log_section "Summary"
echo ""
echo "  Documentation:  $DOC_DIR"
echo "  API Index:      $API_INDEX"
echo "  Crates:         $CRATE_COUNT"
echo ""
echo "  Quick access:"
echo "    Core:     file://$DOC_DIR/dashflow/index.html"
echo "    CLI:      file://$DOC_DIR/dashflow_cli/index.html"
echo "    Stream:   file://$DOC_DIR/dashflow_streaming/index.html"
echo ""
echo "  Commands:"
echo "    View:     ./scripts/generate_docs.sh --open"
echo "    Serve:    ./scripts/generate_docs.sh --serve"
echo "    Single:   ./scripts/generate_docs.sh dashflow-openai"
echo ""
