// Copyright 2026 Dropbox (created by Andrew Yates <ayates@dropbox.com>)

//! Core types for data collection and training examples

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Source of a training example
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DataSource {
    /// Real production data
    Production,
    /// Synthetically generated by LLM
    Synthetic,
    /// Human-labeled data
    HumanLabeled,
}

/// A training example with input, output, and metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingExample {
    /// Input data (text, structured data, etc.)
    pub input: HashMap<String, serde_json::Value>,

    /// Output/label
    pub output: HashMap<String, serde_json::Value>,

    /// Source of this example
    pub source: DataSource,

    /// Quality score (0.0-1.0) for synthetic examples
    #[serde(default)]
    pub quality_score: Option<f64>,

    /// Optional metadata
    #[serde(default)]
    pub metadata: HashMap<String, serde_json::Value>,
}

impl TrainingExample {
    /// Create a new training example
    pub fn new(
        input: HashMap<String, serde_json::Value>,
        output: HashMap<String, serde_json::Value>,
        source: DataSource,
    ) -> Self {
        Self {
            input,
            output,
            source,
            quality_score: None,
            metadata: HashMap::new(),
        }
    }

    /// Create a production example
    pub fn production(
        input: HashMap<String, serde_json::Value>,
        output: HashMap<String, serde_json::Value>,
    ) -> Self {
        Self::new(input, output, DataSource::Production)
    }

    /// Create a synthetic example with quality score
    pub fn synthetic(
        input: HashMap<String, serde_json::Value>,
        output: HashMap<String, serde_json::Value>,
        quality_score: f64,
    ) -> Self {
        Self {
            input,
            output,
            source: DataSource::Synthetic,
            quality_score: Some(quality_score),
            metadata: HashMap::new(),
        }
    }

    /// Get a specific output field as a string
    pub fn get_output_field(&self, field: &str) -> Option<String> {
        self.output.get(field).and_then(|v| match v {
            serde_json::Value::String(s) => Some(s.clone()),
            _ => None,
        })
    }

    /// Get a specific input field as a string
    pub fn get_input_field(&self, field: &str) -> Option<String> {
        self.input.get(field).and_then(|v| match v {
            serde_json::Value::String(s) => Some(s.clone()),
            _ => None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_training_example_creation() {
        let mut input = HashMap::new();
        input.insert("query".to_string(), serde_json::json!("test query"));

        let mut output = HashMap::new();
        output.insert("category".to_string(), serde_json::json!("billing"));

        let example = TrainingExample::production(input, output);

        assert_eq!(example.source, DataSource::Production);
        assert_eq!(
            example.get_input_field("query"),
            Some("test query".to_string())
        );
        assert_eq!(
            example.get_output_field("category"),
            Some("billing".to_string())
        );
    }

    #[test]
    fn test_synthetic_example() {
        let mut input = HashMap::new();
        input.insert("text".to_string(), serde_json::json!("synthetic text"));

        let mut output = HashMap::new();
        output.insert("label".to_string(), serde_json::json!("positive"));

        let example = TrainingExample::synthetic(input, output, 0.85);

        assert_eq!(example.source, DataSource::Synthetic);
        assert_eq!(example.quality_score, Some(0.85));
    }

    #[test]
    fn test_serialization() {
        let mut input = HashMap::new();
        input.insert("query".to_string(), serde_json::json!("test"));

        let mut output = HashMap::new();
        output.insert("answer".to_string(), serde_json::json!("response"));

        let example = TrainingExample::production(input, output);

        let json = serde_json::to_string(&example).unwrap();
        let deserialized: TrainingExample = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.source, DataSource::Production);
        assert_eq!(
            deserialized.get_input_field("query"),
            Some("test".to_string())
        );
    }

    // ============================================================================
    // Additional comprehensive tests
    // ============================================================================

    #[test]
    fn test_data_source_equality() {
        assert_eq!(DataSource::Production, DataSource::Production);
        assert_eq!(DataSource::Synthetic, DataSource::Synthetic);
        assert_eq!(DataSource::HumanLabeled, DataSource::HumanLabeled);

        assert_ne!(DataSource::Production, DataSource::Synthetic);
        assert_ne!(DataSource::Production, DataSource::HumanLabeled);
        assert_ne!(DataSource::Synthetic, DataSource::HumanLabeled);
    }

    #[test]
    fn test_data_source_serialization() {
        let production = DataSource::Production;
        let json = serde_json::to_string(&production).unwrap();
        assert_eq!(json, "\"Production\"");

        let synthetic = DataSource::Synthetic;
        let json = serde_json::to_string(&synthetic).unwrap();
        assert_eq!(json, "\"Synthetic\"");

        let human_labeled = DataSource::HumanLabeled;
        let json = serde_json::to_string(&human_labeled).unwrap();
        assert_eq!(json, "\"HumanLabeled\"");
    }

    #[test]
    fn test_data_source_deserialization() {
        let production: DataSource = serde_json::from_str("\"Production\"").unwrap();
        assert_eq!(production, DataSource::Production);

        let synthetic: DataSource = serde_json::from_str("\"Synthetic\"").unwrap();
        assert_eq!(synthetic, DataSource::Synthetic);

        let human_labeled: DataSource = serde_json::from_str("\"HumanLabeled\"").unwrap();
        assert_eq!(human_labeled, DataSource::HumanLabeled);
    }

    #[test]
    fn test_data_source_clone() {
        let production = DataSource::Production;
        let cloned = production.clone();
        assert_eq!(production, cloned);

        let synthetic = DataSource::Synthetic;
        let cloned = synthetic.clone();
        assert_eq!(synthetic, cloned);
    }

    #[test]
    fn test_data_source_debug() {
        assert_eq!(format!("{:?}", DataSource::Production), "Production");
        assert_eq!(format!("{:?}", DataSource::Synthetic), "Synthetic");
        assert_eq!(format!("{:?}", DataSource::HumanLabeled), "HumanLabeled");
    }

    #[test]
    fn test_training_example_new() {
        let mut input = HashMap::new();
        input.insert("key".to_string(), serde_json::json!("value"));

        let mut output = HashMap::new();
        output.insert("result".to_string(), serde_json::json!("success"));

        let example = TrainingExample::new(input.clone(), output.clone(), DataSource::HumanLabeled);

        assert_eq!(example.source, DataSource::HumanLabeled);
        assert!(example.quality_score.is_none());
        assert!(example.metadata.is_empty());
        assert_eq!(example.input.get("key"), input.get("key"));
        assert_eq!(example.output.get("result"), output.get("result"));
    }

    #[test]
    fn test_training_example_human_labeled() {
        let mut input = HashMap::new();
        input.insert(
            "document".to_string(),
            serde_json::json!("This is a document to classify"),
        );

        let mut output = HashMap::new();
        output.insert("class".to_string(), serde_json::json!("important"));

        let example = TrainingExample::new(input, output, DataSource::HumanLabeled);

        assert_eq!(example.source, DataSource::HumanLabeled);
        assert_eq!(
            example.get_input_field("document"),
            Some("This is a document to classify".to_string())
        );
        assert_eq!(
            example.get_output_field("class"),
            Some("important".to_string())
        );
    }

    #[test]
    fn test_training_example_multiple_fields() {
        let mut input = HashMap::new();
        input.insert("field1".to_string(), serde_json::json!("value1"));
        input.insert("field2".to_string(), serde_json::json!("value2"));
        input.insert("field3".to_string(), serde_json::json!("value3"));

        let mut output = HashMap::new();
        output.insert("out1".to_string(), serde_json::json!("result1"));
        output.insert("out2".to_string(), serde_json::json!("result2"));

        let example = TrainingExample::production(input, output);

        assert_eq!(
            example.get_input_field("field1"),
            Some("value1".to_string())
        );
        assert_eq!(
            example.get_input_field("field2"),
            Some("value2".to_string())
        );
        assert_eq!(
            example.get_input_field("field3"),
            Some("value3".to_string())
        );
        assert_eq!(
            example.get_output_field("out1"),
            Some("result1".to_string())
        );
        assert_eq!(
            example.get_output_field("out2"),
            Some("result2".to_string())
        );
    }

    #[test]
    fn test_training_example_nonexistent_field() {
        let input = HashMap::new();
        let output = HashMap::new();

        let example = TrainingExample::production(input, output);

        assert_eq!(example.get_input_field("nonexistent"), None);
        assert_eq!(example.get_output_field("nonexistent"), None);
    }

    #[test]
    fn test_training_example_non_string_fields() {
        let mut input = HashMap::new();
        input.insert("number".to_string(), serde_json::json!(42));
        input.insert("boolean".to_string(), serde_json::json!(true));
        input.insert("array".to_string(), serde_json::json!([1, 2, 3]));
        input.insert("object".to_string(), serde_json::json!({"nested": "value"}));

        let mut output = HashMap::new();
        output.insert("score".to_string(), serde_json::json!(0.95));

        let example = TrainingExample::production(input, output);

        // Non-string fields should return None from get_*_field methods
        assert_eq!(example.get_input_field("number"), None);
        assert_eq!(example.get_input_field("boolean"), None);
        assert_eq!(example.get_input_field("array"), None);
        assert_eq!(example.get_input_field("object"), None);
        assert_eq!(example.get_output_field("score"), None);
    }

    #[test]
    fn test_training_example_quality_score_range() {
        let input = HashMap::new();
        let output = HashMap::new();

        // Test low quality score
        let low_quality = TrainingExample::synthetic(input.clone(), output.clone(), 0.0);
        assert_eq!(low_quality.quality_score, Some(0.0));

        // Test high quality score
        let high_quality = TrainingExample::synthetic(input.clone(), output.clone(), 1.0);
        assert_eq!(high_quality.quality_score, Some(1.0));

        // Test mid-range quality score
        let mid_quality = TrainingExample::synthetic(input, output, 0.5);
        assert_eq!(mid_quality.quality_score, Some(0.5));
    }

    #[test]
    fn test_training_example_clone() {
        let mut input = HashMap::new();
        input.insert("text".to_string(), serde_json::json!("sample"));

        let mut output = HashMap::new();
        output.insert("label".to_string(), serde_json::json!("test"));

        let example = TrainingExample::synthetic(input, output, 0.9);
        let cloned = example.clone();

        assert_eq!(cloned.source, example.source);
        assert_eq!(cloned.quality_score, example.quality_score);
        assert_eq!(
            cloned.get_input_field("text"),
            example.get_input_field("text")
        );
        assert_eq!(
            cloned.get_output_field("label"),
            example.get_output_field("label")
        );
    }

    #[test]
    fn test_training_example_debug() {
        let mut input = HashMap::new();
        input.insert("key".to_string(), serde_json::json!("val"));

        let output = HashMap::new();

        let example = TrainingExample::production(input, output);

        let debug_str = format!("{:?}", example);
        assert!(debug_str.contains("TrainingExample"));
        assert!(debug_str.contains("Production"));
    }

    #[test]
    fn test_training_example_full_serialization() {
        let mut input = HashMap::new();
        input.insert("question".to_string(), serde_json::json!("What is Rust?"));

        let mut output = HashMap::new();
        output.insert(
            "answer".to_string(),
            serde_json::json!("A systems programming language"),
        );

        let mut example = TrainingExample::synthetic(input, output, 0.95);
        example
            .metadata
            .insert("generator".to_string(), serde_json::json!("gpt-4"));
        example
            .metadata
            .insert("timestamp".to_string(), serde_json::json!("2025-01-01"));

        let json = serde_json::to_string(&example).unwrap();
        let deserialized: TrainingExample = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.source, DataSource::Synthetic);
        assert_eq!(deserialized.quality_score, Some(0.95));
        assert_eq!(
            deserialized.get_input_field("question"),
            Some("What is Rust?".to_string())
        );
        assert_eq!(
            deserialized.get_output_field("answer"),
            Some("A systems programming language".to_string())
        );
        assert_eq!(
            deserialized
                .metadata
                .get("generator")
                .and_then(|v| v.as_str()),
            Some("gpt-4")
        );
    }

    #[test]
    fn test_training_example_deserialize_with_defaults() {
        // Test deserialization when optional fields are missing
        let json = r#"{
            "input": {"q": "test"},
            "output": {"a": "response"},
            "source": "Production"
        }"#;

        let example: TrainingExample = serde_json::from_str(json).unwrap();

        assert_eq!(example.source, DataSource::Production);
        assert!(example.quality_score.is_none());
        assert!(example.metadata.is_empty());
    }

    #[test]
    fn test_training_example_empty_input_output() {
        let input = HashMap::new();
        let output = HashMap::new();

        let example = TrainingExample::production(input, output);

        assert!(example.input.is_empty());
        assert!(example.output.is_empty());
        assert_eq!(example.source, DataSource::Production);
    }

    #[test]
    fn test_training_example_unicode_content() {
        let mut input = HashMap::new();
        input.insert(
            "text".to_string(),
            serde_json::json!("こんにちは世界 🌍 Привет мир"),
        );

        let mut output = HashMap::new();
        output.insert("translation".to_string(), serde_json::json!("Hello World"));

        let example = TrainingExample::production(input, output);

        assert_eq!(
            example.get_input_field("text"),
            Some("こんにちは世界 🌍 Привет мир".to_string())
        );

        // Test serialization roundtrip preserves unicode
        let json = serde_json::to_string(&example).unwrap();
        let deserialized: TrainingExample = serde_json::from_str(&json).unwrap();
        assert_eq!(
            deserialized.get_input_field("text"),
            Some("こんにちは世界 🌍 Привет мир".to_string())
        );
    }

    #[test]
    fn test_training_example_large_content() {
        let mut input = HashMap::new();
        let large_text = "x".repeat(10000);
        input.insert(
            "document".to_string(),
            serde_json::json!(large_text.clone()),
        );

        let mut output = HashMap::new();
        output.insert(
            "summary".to_string(),
            serde_json::json!("Summary of document"),
        );

        let example = TrainingExample::production(input, output);

        assert_eq!(example.get_input_field("document"), Some(large_text));
    }

    #[test]
    fn test_training_example_special_characters() {
        let mut input = HashMap::new();
        input.insert(
            "text".to_string(),
            serde_json::json!("Line1\nLine2\tTabbed\r\nWindows"),
        );

        let output = HashMap::new();

        let example = TrainingExample::production(input, output);

        let json = serde_json::to_string(&example).unwrap();
        let deserialized: TrainingExample = serde_json::from_str(&json).unwrap();

        assert_eq!(
            deserialized.get_input_field("text"),
            Some("Line1\nLine2\tTabbed\r\nWindows".to_string())
        );
    }
}
